version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - /Users/mohanganesh/projects/angular/chat-user-interface/public/:/usr/share/nginx/html:ro
    restart: unless-stopped
